name: angular_google_maps
description: A starting point for Dart libraries or applications.
version: 0.0.4
homepage: https://lefty.io/
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  google_maps: ">=3.2.2 <4.0.0"
  dart_browser_loader: ">=0.0.3 <0.1.0"
  #google_maps_markerclusterer: ">=0.1.0 <1.0.0"
  google_maps_markerclusterer:
    git: https://github.com/leftyio/google-maps-markerclusterer.git

dev_dependencies:
  build: '>=0.11.1 <1.0.0'
  build_runner: '>=0.8.0 <1.0.0'
  build_test: '>=0.10.0 <1.0.0'
  build_web_compilers: '>=0.4.0 <1.0.0'