name: angular_google_maps
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://lefty.io/
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ">=4.0.0 <5.0.0"
  google_maps: ">=3.2.2 <4.0.0"
  dart_browser_loader: ">=0.0.3 <0.1.0"
  google_maps_markerclusterer: ">=0.1.0 <1.0.0"

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
### (default) configuration if this package should be used as a library (import) or if the app should be execute as Dart in Dartium
- angular
### configuration if example web folder should be compiled to js
#- angular:
#    entry_points: example/main.dart
#- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc